index:
    path:      /{type}
    controller: App\Controller\ProductsController::indexPage
    defaults:
        type: index.php
    requirements:
        type: index.php|index.html

product:
    path:      /product/{id}
    controller: App\Controller\ProductsController::getProductList
    methods: GET
    defaults:
        id: all
    
calendar:
    path:      /calendar/
    controller: App\Controller\ProductsController::cartList
    methods: GET
        
cart:
    path:      /cart/{date}
    controller: App\Controller\ProductsController::cartType
    defaults:
        date: '0000-00-00'
    methods: GET
        
cartType:
    path:      /cart/{date}/{id}
    controller: App\Controller\ProductsController::cartType
    defaults:
        date: 0000-00-00, id:0
    methods: POST|DELETE|PUT
